import 'dart:io';
import 'package:path/path.dart' as p;
import 'ai_config_service.dart';
import 'workspace_manifest_service.dart';

class ScanFileTarget {
  final String projectName;
  final String projectPath;
  final String relativePath;
  final File file;

  const ScanFileTarget({
    required this.projectName,
    required this.projectPath,
    required this.relativePath,
    required this.file,
  });
}

class TextChunk {
  final int index;
  final String content;
  final int tokenCount;

  const TextChunk({
    required this.index,
    required this.content,
    required this.tokenCount,
  });
}

/// Service that scans Shepherd projects and workspaces, chunking code files into semantic chunks.
class AiWorkspaceScannerService {
  final String basePath;

  AiWorkspaceScannerService([String? path]) : basePath = path ?? Directory.current.path;

  static const supportedExtensions = {
    '.dart',
    '.yaml',
    '.json',
    '.md',
    '.js',
    '.ts',
    '.tsx',
    '.jsx',
    '.py',
    '.go',
    '.rs',
    '.html',
    '.css',
    '.sql',
    '.sh',
    '.swift',
    '.kt',
    // Plain text, docs and data — what non-developers tend to write.
    '.txt',
    '.rst',
    '.csv',
    '.tsv',
    '.xml',
    '.toml',
    '.ini',
    '.cfg',
    '.properties',
    '.graphql',
    '.proto',
    // More web.
    '.htm',
    '.scss',
    '.sass',
    '.less',
    '.vue',
    '.svelte',
    '.astro',
    // More languages and scripts.
    '.php',
    '.rb',
    '.java',
    '.kts',
    '.gradle',
    '.c',
    '.h',
    '.cpp',
    '.hpp',
    '.cs',
    '.lua',
    '.r',
    '.bash',
    '.zsh',
    '.ps1',
    '.bat',
  };

  /// Files above this size are skipped: a big CSV or JSON dump would turn into
  /// hundreds of chunks (and embedding calls) of little use for answering.
  /// Default; override with `rag_max_file_kb` in ai_config.yaml or the
  /// `SHEPHERD_RAG_MAX_FILE_KB` environment variable (the latter wins).
  static const maxIndexableBytes = 256 * 1024;
  static const _minKb = 1;
  static const _maxKb = 10 * 1024;

  /// Effective limit in bytes: env var, then config, then the default.
  /// Values outside 1 KB..10 MB or not numbers fall through to the next source.
  static int resolveMaxBytes({AiConfigModel? config, Map<String, String>? env}) {
    int? valid(Object? v) {
      final kb = int.tryParse(v?.toString() ?? '');
      return kb != null && kb >= _minKb && kb <= _maxKb ? kb : null;
    }

    final kb = valid((env ?? Platform.environment)['SHEPHERD_RAG_MAX_FILE_KB']) ??
        valid(config?.ragMaxFileKb);
    return kb == null ? maxIndexableBytes : kb * 1024;
  }

  late int _maxBytes = maxIndexableBytes;

  /// Generated by package managers; large and never useful as context. (`.lock`
  /// files are already excluded by pattern below.)
  static const excludedFileNames = {
    'package-lock.json',
    'npm-shrinkwrap.json',
    'pnpm-lock.yaml',
  };

  static const excludedDirs = {
    '.git',
    '.dart_tool',
    '.shepherd',
    'build',
    'node_modules',
    '.idea',
    '.vscode',
    'dist',
    '.gradle',
    'Pods',
    'coverage',
    '.fvm',
  };

  static const excludedFilePatterns = {
    '.g.dart',
    '.freezed.dart',
    '.lock',
    '.min.js',
    '.min.css',
  };

  /// The company Wiki that Shepherd Studio keeps as Markdown in
  /// `.shepherd/wiki/` is indexed as a project of its own, since the scan
  /// skips hidden folders. It is searchable whatever projects are selected.
  static const wikiProjectName = 'Wiki';

  Directory get wikiDir => Directory(p.join(basePath, '.shepherd', 'wiki'));

  void _scanWiki(List<ScanFileTarget> out) {
    final dir = wikiDir;
    if (!dir.existsSync()) return;
    for (final f in dir.listSync(followLinks: false).whereType<File>()) {
      final name = p.basename(f.path);
      if (!name.endsWith('.md') || f.lengthSync() > _maxBytes) continue;
      out.add(ScanFileTarget(
        projectName: wikiProjectName,
        projectPath: dir.path,
        relativePath: name,
        file: f,
      ));
    }
  }

  /// Discovers projects and files to be indexed.
  List<ScanFileTarget> discoverFiles({String? specificProject}) {
    final targets = <ScanFileTarget>[];
    _maxBytes = resolveMaxBytes(config: AiConfigService().load());
    if (specificProject?.toLowerCase() == wikiProjectName.toLowerCase()) {
      _scanWiki(targets);
      return targets;
    }
    if (specificProject == null) _scanWiki(targets);
    final manifest = WorkspaceManifest.tryLoad();

    if (manifest != null && manifest.projects.isNotEmpty) {
      for (final proj in manifest.projects) {
        if (specificProject != null &&
            proj.name.toLowerCase() != specificProject.toLowerCase() &&
            proj.id.toLowerCase() != specificProject.toLowerCase()) {
          continue;
        }

        final projDir = Directory(p.isAbsolute(proj.path) ? proj.path : p.join(basePath, proj.path));
        if (projDir.existsSync()) {
          _scanDirectory(projDir, proj.name, projDir.path, targets);
        }
      }
    } else {
      // Standalone or single project
      final projName = manifest?.name ?? p.basename(basePath);
      final currentDir = Directory(basePath);
      _scanDirectory(currentDir, projName, basePath, targets);
    }

    return targets;
  }

  void _scanDirectory(
    Directory dir,
    String projectName,
    String projectRoot,
    List<ScanFileTarget> outTargets,
  ) {
    try {
      final entries = dir.listSync(followLinks: false);
      for (final entry in entries) {
        final name = p.basename(entry.path);
        if (entry is Directory) {
          if (excludedDirs.contains(name) || name.startsWith('.')) continue;
          _scanDirectory(entry, projectName, projectRoot, outTargets);
        } else if (entry is File) {
          if (_isIndexableFile(name) && entry.lengthSync() <= _maxBytes) {
            final relPath = p.relative(entry.path, from: projectRoot).replaceAll('\\', '/');
            outTargets.add(ScanFileTarget(
              projectName: projectName,
              projectPath: projectRoot,
              relativePath: relPath,
              file: entry,
            ));
          }
        }
      }
    } catch (_) {}
  }

  bool _isIndexableFile(String filename) {
    if (excludedFileNames.contains(filename)) return false;
    for (final pattern in excludedFilePatterns) {
      if (filename.endsWith(pattern)) return false;
    }
    final ext = p.extension(filename).toLowerCase();
    return supportedExtensions.contains(ext);
  }

  /// Splits file content into overlapping chunks to preserve semantic context.
  List<TextChunk> chunkFile(String content, String relativePath, {int maxChunkChars = 1000, int overlapChars = 150}) {
    final trimmed = content.trim();
    if (trimmed.isEmpty) return [];

    if (trimmed.length <= maxChunkChars) {
      final header = '// File: $relativePath\n';
      final text = '$header$trimmed';
      return [
        TextChunk(
          index: 0,
          content: text,
          tokenCount: (text.length / 4).ceil(),
        ),
      ];
    }

    final chunks = <TextChunk>[];
    final lines = trimmed.split('\n');
    final currentBuffer = StringBuffer();
    var chunkIndex = 0;

    for (final line in lines) {
      if (currentBuffer.length + line.length > maxChunkChars && currentBuffer.isNotEmpty) {
        final rawText = currentBuffer.toString().trim();
        final text = '// File: $relativePath (part ${chunkIndex + 1})\n$rawText';
        chunks.add(TextChunk(
          index: chunkIndex++,
          content: text,
          tokenCount: (text.length / 4).ceil(),
        ));

        // Preserve trailing lines for overlap context
        final bufferLines = rawText.split('\n');
        currentBuffer.clear();
        final overlapLines = bufferLines.length > 5 ? bufferLines.sublist(bufferLines.length - 4) : bufferLines;
        for (final oLine in overlapLines) {
          currentBuffer.writeln(oLine);
        }
      }
      currentBuffer.writeln(line);
    }

    if (currentBuffer.isNotEmpty) {
      final rawText = currentBuffer.toString().trim();
      if (rawText.isNotEmpty) {
        final text = '// File: $relativePath (part ${chunkIndex + 1})\n$rawText';
        chunks.add(TextChunk(
          index: chunkIndex,
          content: text,
          tokenCount: (text.length / 4).ceil(),
        ));
      }
    }

    return chunks;
  }
}
